/* Text for the dashboard frame, chat sessions, mentor flow, settings and landing page. */
import T, { type Lang } from "./text-app";

const ADD: Record<Lang, Record<string, string>> = {
  en: {
    navDash: "Dashboard", navSettings: "Settings", bellH: "Notifications", bellEmpty: "You're all caught up.", bellReply: "Your mentor replied", roleMentor: "Mentor",
    newChat: "New chat", chats: "Chats", noChats: "No chats yet. Ask your first question.", deleteChat: "Delete chat", confirmDelete: "Delete this chat and everything in it?",
    handling: "{name} is looking at your question.", replied: "{name} replied", yourMentor: "Your mentor",
    mTaken: "✓ You've taken this question. Other mentors now see it as taken.", mTakenBy: "Taken by {name}", mTakenYou: "Taken by you",
    mReleased: "Released. It's back in the shared inbox.", mSentTo: "Sent to {name} in {lang}. It's now in Answered.",
    mErrTranslate: "Translation isn't available right now. Your reply is still here, so please try again.", mErr: "Something went wrong. Please try again.",
    setProfile: "Your profile", setName: "First name", setLang: "App language", setRead: "Can you read Arabic?", setWork: "When do you usually work?",
    setPhone: "Mentor may call or WhatsApp me", setPhoneNum: "Phone number, with country code", setSave: "Save changes", setSaved: "Saved.", setAccount: "Account",
    lnFeatures: "Features", lnHow: "How it works", lnOpen: "Open Mu'adh", lnSignup: "Create a free account", lnLogin: "Sign in",
    lnHeroT: "Your first steps in Islam, with a guide by your side", lnHeroP: "Mu'adh is a gentle companion for new Muslims: one small lesson a day, prayer times and reminders, and answers from trusted sources, with a real mentor always in the loop.",
    lnF1T: "Step-by-step lessons", lnF1P: "40 short lessons in the right order, from the shahada to your first prayer and daily life.",
    lnF2T: "Answers you can trust", lnF2P: "Answers come only from the Quran and authentic hadith, shown word for word with their source.",
    lnF3T: "A real mentor", lnF3P: "Personal questions go to a da'i of the same gender, who replies in Arabic. You receive it in your language.",
    lnF4T: "Prayer made easy", lnF4P: "Prayer times for your city, a live countdown, reminders, and a planner for night shifts.",
    lnF5T: "Qibla compass", lnF5P: "Find the direction of the Kaaba wherever you are, with a live compass.",
    lnF6T: "In your language", lnF6P: "English, Arabic and Bangla, and you can ask in any language.",
    lnS1T: "Create your account", lnS1P: "Tell us a little about yourself, in under a minute.",
    lnS2T: "Learn a little each day", lnS2P: "Follow your lessons and build your daily prayer routine.",
    lnS3T: "Ask anything", lnS3P: "Get a sourced answer, or a reply from your mentor for anything personal.",
    lnTrustT: "Built on approved sources", lnTrustP: "Quran translations from the King Fahd Complex (QuranEnc), hadith from Bukhari and Muslim (HadeethEnc), checked on Dorar.net.",
    lnCtaT: "Begin your journey today", lnFoot: "Team Sabeel · AI Challenge Serving Islamic Content",
  },
  ar: {
    navDash: "لوحة التحكم", navSettings: "الإعدادات", bellH: "التنبيهات", bellEmpty: "لا جديد الآن.", bellReply: "ردّ مرشدك", roleMentor: "مرشد",
    newChat: "محادثة جديدة", chats: "المحادثات", noChats: "لا توجد محادثات بعد. اطرح سؤالك الأول.", deleteChat: "حذف المحادثة", confirmDelete: "هل تريد حذف هذه المحادثة وكل ما فيها؟",
    handling: "{name} يطّلع على سؤالك الآن.", replied: "ردّ {name}", yourMentor: "مرشدك",
    mTaken: "✓ توليت هذا السؤال. يراه المرشدون الآخرون محجوزًا الآن.", mTakenBy: "يتولاه {name}", mTakenYou: "تتولاه أنت",
    mReleased: "تم إلغاء التولي. عاد السؤال إلى الصندوق المشترك.", mSentTo: "أُرسل إلى {name} بلغة {lang}. أصبح الآن في «تم الرد».",
    mErrTranslate: "الترجمة غير متاحة الآن. ردّك محفوظ هنا، فحاول مرة أخرى.", mErr: "حدث خطأ. حاول مرة أخرى.",
    setProfile: "ملفك", setName: "الاسم الأول", setLang: "لغة التطبيق", setRead: "هل تقرأ العربية؟", setWork: "متى تعمل عادة؟",
    setPhone: "يمكن لمرشدي الاتصال بي أو مراسلتي عبر واتساب", setPhoneNum: "رقم الجوال مع رمز الدولة", setSave: "حفظ التغييرات", setSaved: "تم الحفظ.", setAccount: "الحساب",
    lnFeatures: "المزايا", lnHow: "كيف يعمل", lnOpen: "افتح معاذ", lnSignup: "أنشئ حسابًا مجانيًا", lnLogin: "تسجيل الدخول",
    lnHeroT: "خطواتك الأولى في الإسلام، ومعك من يرشدك", lnHeroP: "معاذ رفيق لطيف للمسلمين الجدد: درس قصير كل يوم، ومواقيت الصلاة والتذكير بها، وإجابات من مصادر موثوقة، مع مرشد حقيقي دائمًا.",
    lnF1T: "دروس خطوة بخطوة", lnF1P: "٤٠ درسًا قصيرًا بالترتيب الصحيح، من الشهادة إلى أول صلاة والحياة اليومية.",
    lnF2T: "إجابات موثوقة", lnF2P: "الإجابات من القرآن والحديث الصحيح فقط، تُعرض بنصها مع مصدرها.",
    lnF3T: "مرشد حقيقي", lnF3P: "الأسئلة الشخصية تذهب إلى داعية من الجنس نفسه يرد بالعربية، وتصلك بلغتك.",
    lnF4T: "الصلاة بسهولة", lnF4P: "مواقيت الصلاة لمدينتك، وعدّ تنازلي مباشر، وتذكير، ومخطط للمناوبات الليلية.",
    lnF5T: "بوصلة القبلة", lnF5P: "اعرف اتجاه الكعبة أينما كنت ببوصلة حية.",
    lnF6T: "بلغتك", lnF6P: "الإنجليزية والعربية والبنغالية، ويمكنك السؤال بأي لغة.",
    lnS1T: "أنشئ حسابك", lnS1P: "أخبرنا قليلًا عن نفسك في أقل من دقيقة.",
    lnS2T: "تعلّم قليلًا كل يوم", lnS2P: "تابع دروسك وابنِ روتين صلاتك اليومي.",
    lnS3T: "اسأل عن أي شيء", lnS3P: "احصل على إجابة موثقة، أو رد من مرشدك في الأمور الشخصية.",
    lnTrustT: "مبني على مصادر معتمدة", lnTrustP: "ترجمات القرآن من مجمع الملك فهد (QuranEnc)، والأحاديث من البخاري ومسلم (HadeethEnc)، مع التحقق في الدرر السنية.",
    lnCtaT: "ابدأ رحلتك اليوم", lnFoot: "فريق سبيل · تحدي الذكاء الاصطناعي لخدمة المحتوى الإسلامي",
  },
  bn: {
    navDash: "ড্যাশবোর্ড", navSettings: "সেটিংস", bellH: "নোটিফিকেশন", bellEmpty: "নতুন কিছু নেই।", bellReply: "আপনার মেন্টর উত্তর দিয়েছেন", roleMentor: "মেন্টর",
    newChat: "নতুন চ্যাট", chats: "চ্যাটসমূহ", noChats: "এখনো কোনো চ্যাট নেই। প্রথম প্রশ্নটি করুন।", deleteChat: "চ্যাট মুছুন", confirmDelete: "এই চ্যাট ও এর সবকিছু মুছে ফেলবেন?",
    handling: "{name} আপনার প্রশ্নটি দেখছেন।", replied: "{name} উত্তর দিয়েছেন", yourMentor: "আপনার মেন্টর",
    mTaken: "✓ আপনি প্রশ্নটি নিয়েছেন। অন্য মেন্টররা এখন এটি নেওয়া হয়েছে দেখবেন।", mTakenBy: "{name} নিয়েছেন", mTakenYou: "আপনি নিয়েছেন",
    mReleased: "ছেড়ে দেওয়া হয়েছে। প্রশ্নটি আবার সবার ইনবক্সে।", mSentTo: "{name}-কে {lang} ভাষায় পাঠানো হয়েছে। এখন এটি «উত্তর দেওয়া»-তে।",
    mErrTranslate: "এখন অনুবাদ করা যাচ্ছে না। আপনার উত্তর এখানেই আছে, আবার চেষ্টা করুন।", mErr: "কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    setProfile: "আপনার প্রোফাইল", setName: "প্রথম নাম", setLang: "অ্যাপের ভাষা", setRead: "আপনি কি আরবি পড়তে পারেন?", setWork: "আপনি সাধারণত কখন কাজ করেন?",
    setPhone: "মেন্টর আমাকে কল বা হোয়াটসঅ্যাপ করতে পারবেন", setPhoneNum: "ফোন নম্বর, দেশের কোডসহ", setSave: "পরিবর্তন সংরক্ষণ করুন", setSaved: "সংরক্ষিত হয়েছে।", setAccount: "অ্যাকাউন্ট",
    lnFeatures: "বৈশিষ্ট্য", lnHow: "যেভাবে কাজ করে", lnOpen: "মুআয খুলুন", lnSignup: "বিনামূল্যে অ্যাকাউন্ট খুলুন", lnLogin: "সাইন ইন",
    lnHeroT: "ইসলামে আপনার প্রথম পদক্ষেপ, পাশে একজন পথপ্রদর্শক", lnHeroP: "মুআয নতুন মুসলিমদের এক কোমল সঙ্গী: প্রতিদিন একটি ছোট পাঠ, নামাজের সময় ও রিমাইন্ডার, আর বিশ্বস্ত উৎস থেকে উত্তর, সাথে সবসময় একজন সত্যিকারের মেন্টর।",
    lnF1T: "ধাপে ধাপে পাঠ", lnF1P: "সঠিক ক্রমে ৪০টি ছোট পাঠ, শাহাদা থেকে প্রথম নামাজ ও দৈনন্দিন জীবন পর্যন্ত।",
    lnF2T: "নির্ভরযোগ্য উত্তর", lnF2P: "উত্তর আসে শুধু কুরআন ও সহীহ হাদিস থেকে, হুবহু উৎসসহ।",
    lnF3T: "সত্যিকারের মেন্টর", lnF3P: "ব্যক্তিগত প্রশ্ন যায় একই লিঙ্গের একজন দাঈর কাছে, তিনি আরবিতে উত্তর দেন, আপনি পান নিজের ভাষায়।",
    lnF4T: "সহজ নামাজ", lnF4P: "আপনার শহরের নামাজের সময়, লাইভ কাউন্টডাউন, রিমাইন্ডার আর রাতের শিফটের পরিকল্পনা।",
    lnF5T: "কিবলা কম্পাস", lnF5P: "যেখানেই থাকুন, লাইভ কম্পাসে কাবার দিক জানুন।",
    lnF6T: "আপনার ভাষায়", lnF6P: "ইংরেজি, আরবি ও বাংলা, আর যেকোনো ভাষায় প্রশ্ন করা যায়।",
    lnS1T: "অ্যাকাউন্ট খুলুন", lnS1P: "এক মিনিটের মধ্যে নিজের সম্পর্কে একটু জানান।",
    lnS2T: "প্রতিদিন একটু শিখুন", lnS2P: "পাঠ অনুসরণ করুন আর প্রতিদিনের নামাজের অভ্যাস গড়ুন।",
    lnS3T: "যেকোনো প্রশ্ন করুন", lnS3P: "উৎসসহ উত্তর পান, আর ব্যক্তিগত বিষয়ে মেন্টরের উত্তর।",
    lnTrustT: "অনুমোদিত উৎসের ওপর নির্মিত", lnTrustP: "কুরআনের অনুবাদ বাদশাহ ফাহাদ কমপ্লেক্স থেকে (QuranEnc), হাদিস বুখারি ও মুসলিম থেকে (HadeethEnc), Dorar.net-এ যাচাই করা।",
    lnCtaT: "আজই আপনার যাত্রা শুরু করুন", lnFoot: "টিম সাবিল · ইসলামিক কনটেন্ট সেবায় এআই চ্যালেঞ্জ",
  },
};
(Object.keys(ADD) as Lang[]).forEach((l) => Object.assign(T[l], ADD[l]));
export default T;

const PRAYER: Record<Lang, Record<string, string>> = {
  en: { setPrayer: "Prayer times", setPrayerP: "We use the method followed where you are. Change it only if your local mosque uses a different one.", setMethod: "Calculation method", setAsr: "Asr time", setAuto: "Automatic for my location", setStandard: "Standard (Shafi'i, Maliki, Hanbali)" },
  ar: { setPrayer: "مواقيت الصلاة", setPrayerP: "نستخدم الطريقة المتبعة في بلدك. غيّرها فقط إن كان مسجدك يتبع طريقة أخرى.", setMethod: "طريقة الحساب", setAsr: "وقت العصر", setAuto: "تلقائي حسب موقعي", setStandard: "الجمهور (الشافعي والمالكي والحنبلي)" },
  bn: { setPrayer: "নামাজের সময়", setPrayerP: "আপনি যেখানে আছেন সেখানকার পদ্ধতি ব্যবহার করা হয়। আপনার মসজিদ অন্য পদ্ধতি মানলে তবেই বদলান।", setMethod: "হিসাবের পদ্ধতি", setAsr: "আসরের সময়", setAuto: "আমার লোকেশন অনুযায়ী স্বয়ংক্রিয়", setStandard: "সাধারণ (শাফেয়ি, মালেকি, হাম্বলি)" },
};
(Object.keys(PRAYER) as Lang[]).forEach((l) => Object.assign(T[l], PRAYER[l]));
