/* Text added for the real app: accounts, onboarding, reminders, tracker, pop-ups. */
import T, { type Lang } from "./text";

const ADD: Record<Lang, Record<string, string>> = {
  en: {
    signupH: "Create your account", signupP: "Your lessons, questions and your mentor's replies stay saved in one place.",
    loginH: "Welcome back", loginP: "Sign in to continue your journey.",
    nameL: "First name", emailL: "Email", passL: "Password", passHint: "At least 8 characters",
    genderQ: "Are you a brother or a sister?", brother: "Brother", sister: "Sister",
    genderWhy: "We ask this only to connect you with a mentor of the same gender.",
    langQ: "Your language", create: "Create account", signIn: "Sign in", signOut: "Sign out",
    haveAcc: "Already have an account?", noAcc: "New to Mu'adh?", signUpLink: "Create an account",
    errLogin: "Email or password is not correct.", errPass: "Password must be at least 8 characters.",
    errGender: "Please choose brother or sister.", errName: "Please enter your first name.", errGeneric: "Something went wrong. Please try again.",
    errTaken: "An account with this email already exists. Try signing in.",
    phoneQ: "Would you like your mentor to be able to call or WhatsApp you?", phoneOpt: "Optional",
    phoneYes: "Yes, they can contact me", phoneNo: "No, keep it in the app", phoneL: "Phone number, with country code",
    phoneNote: "Only your own mentor can see it, and only because you said yes.", finish: "Finish",
    loading: "Loading…", saving: "Saving…",
    remOn: "Turn on prayer reminders", remActive: "Prayer reminders are on", remBlocked: "Notifications are blocked in your browser settings.",
    remTitle: "Time for {p}", remBody: "It's time to pray {p}. May Allah accept it from you.",
    remNote: "Reminders work while Mu'adh is open. For reminders when your phone is locked, add prayer times to your calendar.",
    trackH: "My prayers today", trackP: "Tap each prayer once you've prayed it.", trackDone: "{n} of 5 prayed",
    trackAll: "All five prayers today. Alhamdulillah!",
    ayahH: "Verse of the day", ayahSrc: "Translation: King Fahd Complex, via QuranEnc", close: "Close",
    sleepH: "Before you sleep", wakeH: "Good morning",
    jumuahIn: "Jumu'ah in {d} days", jumuahTomorrow: "Jumu'ah is tomorrow", jumuahToday: "Today is Friday: Jumu'ah prayer",
    shiftNote: "Night shifts: we'll remind you before each prayer.", lessonN: "Lesson {n} of 40", useLoc: "Use my location",
  },
  ar: {
    signupH: "أنشئ حسابك", signupP: "تبقى دروسك وأسئلتك وردود مرشدك محفوظة في مكان واحد.",
    loginH: "مرحبًا بعودتك", loginP: "سجّل الدخول لمتابعة رحلتك.",
    nameL: "الاسم الأول", emailL: "البريد الإلكتروني", passL: "كلمة المرور", passHint: "ثمانية أحرف على الأقل",
    genderQ: "هل أنت أخ أم أخت؟", brother: "أخ", sister: "أخت",
    genderWhy: "نسأل عن هذا فقط لنربطك بمرشد من الجنس نفسه.",
    langQ: "لغتك", create: "إنشاء الحساب", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج",
    haveAcc: "لديك حساب؟", noAcc: "جديد في معاذ؟", signUpLink: "أنشئ حسابًا",
    errLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة.", errPass: "يجب أن تكون كلمة المرور ثمانية أحرف على الأقل.",
    errGender: "يرجى اختيار أخ أو أخت.", errName: "يرجى كتابة اسمك الأول.", errGeneric: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    errTaken: "يوجد حساب بهذا البريد الإلكتروني. جرّب تسجيل الدخول.",
    phoneQ: "هل تود أن يتمكن مرشدك من الاتصال بك أو مراسلتك عبر واتساب؟", phoneOpt: "اختياري",
    phoneYes: "نعم، يمكنه التواصل معي", phoneNo: "لا، أفضّل البقاء داخل التطبيق", phoneL: "رقم الجوال مع رمز الدولة",
    phoneNote: "لا يراه إلا مرشدك، ولأنك وافقت فقط.", finish: "إنهاء",
    loading: "جارٍ التحميل…", saving: "جارٍ الحفظ…",
    remOn: "تفعيل تذكير الصلاة", remActive: "تذكير الصلاة مفعّل", remBlocked: "الإشعارات محظورة في إعدادات المتصفح.",
    remTitle: "حان وقت {p}", remBody: "حان وقت صلاة {p}. تقبّل الله منك.",
    remNote: "يعمل التذكير ما دام معاذ مفتوحًا. للتذكير والجوال مقفل، أضف مواقيت الصلاة إلى تقويمك.",
    trackH: "صلواتي اليوم", trackP: "اضغط على كل صلاة بعد أن تؤديها.", trackDone: "{n} من ٥ صلوات",
    trackAll: "الصلوات الخمس اليوم. الحمد لله!",
    ayahH: "آية اليوم", ayahSrc: "من القرآن الكريم، عبر QuranEnc", close: "إغلاق",
    sleepH: "قبل النوم", wakeH: "صباح الخير",
    jumuahIn: "الجمعة بعد {d} أيام", jumuahTomorrow: "الجمعة غدًا", jumuahToday: "اليوم الجمعة: صلاة الجمعة",
    shiftNote: "مناوبات ليلية: سنذكّرك قبل كل صلاة.", lessonN: "الدرس {n} من ٤٠", useLoc: "استخدم موقعي",
  },
  bn: {
    signupH: "আপনার অ্যাকাউন্ট তৈরি করুন", signupP: "আপনার পাঠ, প্রশ্ন আর মেন্টরের উত্তর এক জায়গায় সংরক্ষিত থাকবে।",
    loginH: "আবার স্বাগতম", loginP: "আপনার যাত্রা চালিয়ে যেতে সাইন ইন করুন।",
    nameL: "প্রথম নাম", emailL: "ইমেইল", passL: "পাসওয়ার্ড", passHint: "কমপক্ষে ৮টি অক্ষর",
    genderQ: "আপনি কি ভাই না বোন?", brother: "ভাই", sister: "বোন",
    genderWhy: "শুধু একই লিঙ্গের মেন্টরের সাথে যুক্ত করার জন্য আমরা এটি জানতে চাই।",
    langQ: "আপনার ভাষা", create: "অ্যাকাউন্ট তৈরি করুন", signIn: "সাইন ইন", signOut: "সাইন আউট",
    haveAcc: "ইতিমধ্যে অ্যাকাউন্ট আছে?", noAcc: "মুআযে নতুন?", signUpLink: "অ্যাকাউন্ট তৈরি করুন",
    errLogin: "ইমেইল বা পাসওয়ার্ড সঠিক নয়।", errPass: "পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে।",
    errGender: "অনুগ্রহ করে ভাই বা বোন বেছে নিন।", errName: "অনুগ্রহ করে আপনার প্রথম নাম লিখুন।", errGeneric: "কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    errTaken: "এই ইমেইলে আগে থেকেই অ্যাকাউন্ট আছে। সাইন ইন করে দেখুন।",
    phoneQ: "আপনার মেন্টর কি আপনাকে কল বা হোয়াটসঅ্যাপ করতে পারবেন?", phoneOpt: "ঐচ্ছিক",
    phoneYes: "হ্যাঁ, যোগাযোগ করতে পারবেন", phoneNo: "না, অ্যাপের ভেতরেই থাকুক", phoneL: "ফোন নম্বর, দেশের কোডসহ",
    phoneNote: "শুধু আপনার নিজের মেন্টর এটি দেখতে পাবেন, আর তা শুধু আপনার সম্মতিতে।", finish: "শেষ করুন",
    loading: "লোড হচ্ছে…", saving: "সংরক্ষণ হচ্ছে…",
    remOn: "নামাজের রিমাইন্ডার চালু করুন", remActive: "নামাজের রিমাইন্ডার চালু আছে", remBlocked: "ব্রাউজারের সেটিংসে নোটিফিকেশন বন্ধ করা আছে।",
    remTitle: "{p}-এর সময়", remBody: "{p} নামাজের সময় হয়েছে। আল্লাহ কবুল করুন।",
    remNote: "মুআয খোলা থাকলে রিমাইন্ডার কাজ করে। ফোন লক থাকলেও রিমাইন্ডার পেতে নামাজের সময় ক্যালেন্ডারে যোগ করুন।",
    trackH: "আজ আমার নামাজ", trackP: "নামাজ পড়ার পর প্রতিটিতে চাপুন।", trackDone: "৫টির মধ্যে {n}টি পড়া হয়েছে",
    trackAll: "আজ পাঁচ ওয়াক্ত নামাজই পড়া হয়েছে। আলহামদুলিল্লাহ!",
    ayahH: "আজকের আয়াত", ayahSrc: "অনুবাদ: বাদশাহ ফাহাদ কমপ্লেক্স, QuranEnc থেকে", close: "বন্ধ করুন",
    sleepH: "ঘুমানোর আগে", wakeH: "শুভ সকাল",
    jumuahIn: "জুমা {d} দিন পর", jumuahTomorrow: "জুমা আগামীকাল", jumuahToday: "আজ শুক্রবার: জুমার নামাজ",
    shiftNote: "রাতের শিফট: প্রতিটি নামাজের আগে আমরা মনে করিয়ে দেব।", lessonN: "৪০টির মধ্যে {n}তম পাঠ", useLoc: "আমার লোকেশন ব্যবহার করুন",
  },
};
(Object.keys(ADD) as Lang[]).forEach((l) => Object.assign(T[l], ADD[l]));

export default T;
export type { Lang };
