/* UI text in English, Arabic and Bangla. */
/* eslint-disable @typescript-eslint/no-explicit-any */
export type Lang = "en" | "ar" | "bn";
const T: Record<Lang, Record<string, any>> = {
en:{navHome:"Today",navLessons:"Lessons",navAsk:"Ask",navDuas:"Duas",navQibla:"Qibla",portal:"Mentor portal",portalShort:"Mentor",
 greet:"Assalamu alaikum, Karim",heroP:"Three weeks into your journey. One small step today is enough.",nextK:"Next prayer",inT:"in",locNote:"Times for your location",locFallback:"Times for Tabuk. Allow location for your city.",
 todayStep:"Today's step",lessonOf:"Lesson 11 of 40",cont:"Continue lesson",stage:["Faith","Purity","Prayer","Daily life","Practice"],
 times:"Prayer times",qibla:"Qibla",qiblaSub:"Find the direction of the Kaaba",duas:"Duas",duasSub:"Eating, washroom, sleep, hard times",
 dhikr:["SubhanAllah","Alhamdulillah","Allahu Akbar"],dhikrSub:"Tap the circle. 33 times each, after every prayer.",
 prayers:["Fajr","Dhuhr","Asr","Maghrib","Isha"],
 back:"Back",l11:"Wudu step by step",l11lead:"Wudu is the washing you do before prayer. Allah describes it in the Quran, and the companion Uthman showed how the Prophet (peace be upon him) made it.",
 l11steps:["Make the intention in your heart to do wudu.","Wash your hands three times.","Rinse your mouth, and rinse your nose by drawing in a little water and blowing it out.","Wash your face three times, from the hairline to the chin and from ear to ear.","Wash your right arm up to and including the elbow three times, then the left.","Wipe your head once with wet hands.","Wash your right foot up to and including the ankle three times, then the left."],
 fromQuran:"From the Quran",fromHadith:"From the Sunnah",verseNote:"The verse in Arabic, with the King Fahd Complex translation.",hadithNote:"The hadith text, with its grade from Dorar.net.",
 key:"Key point",keyT:"Wudu washes the face, arms, head and feet, in order, before prayer.",tryT:"Try this today",tryTT:"Make wudu once, slowly, following these steps.",askM:"Ask your mentor",askMT:"What to do about a cast, a bandage or nail polish that stops water reaching the skin.",
 done:"Mark as done",doneOk:"Well done. Lesson 12 is ready for you.",
 lessonsH:"Your learning journey",lessonsP:"Forty short lessons, in the order the Prophet (peace be upon him) taught Mu'adh: belief first, then prayer, then the rest.",
 stageNames:["Foundations of faith","Purification","Prayer","Daily life","The wider practice"],lessonsWord:"lessons",completed:"completed",open:"Open",
 askH:"Ask anything",askP:"In your own language. Answers come only from approved sources, and personal questions go to your mentor.",ph:"Type your question",send:"Ask",
 sugg:["How do I make wudu?","My wife is Christian. Is our marriage still valid?","\"Seek knowledge even in China.\" Is it a hadith?"],
 searching:"Looking in approved sources…",sources:"Sources",openLesson:"Open the full lesson",
 refH:"This one is for your mentor",refP:"It is a personal question about your own situation, so it needs a person who knows the details. I have sent it to your mentor, and the reply will appear here in English.",
 nfH:"Not found in our sources",nfP:"I couldn't find this saying in the hadith collections we use. That alone does not decide whether it is authentic. Dorar.net's grade and the scholar it comes from are shown here in the full app, and your mentor can tell you more.",
 fallback:"In this preview, try one of the suggested questions. The full app answers any question.",
 mentorSays:"Your mentor replied",
 duasH:"Duas for every day",duasP:"Short duas from the Sunnah, with meaning and source.",
 dcat:["Before eating","Entering the washroom","Before sleeping","On waking","In hard times"],
 qH:"Qibla direction",qP:"Face this direction for prayer. On a phone, the dial turns with your compass.",qFrom:"from your location",qFromT:"from Tabuk",qBtn:"Use my location",
 audio:"Audio by our hafiz plays here in the full app."},
ar:{navHome:"اليوم",navLessons:"الدروس",navAsk:"اسأل",navDuas:"الأدعية",navQibla:"القبلة",portal:"بوابة المرشد",portalShort:"المرشد",
 greet:"السلام عليكم يا كريم",heroP:"ثلاثة أسابيع في رحلتك. خطوة صغيرة اليوم تكفي.",nextK:"الصلاة القادمة",inT:"بعد",locNote:"المواقيت حسب موقعك",locFallback:"مواقيت تبوك. اسمح بالموقع لمعرفة مواقيت مدينتك.",
 todayStep:"خطوة اليوم",lessonOf:"الدرس ١١ من ٤٠",cont:"أكمل الدرس",stage:["الإيمان","الطهارة","الصلاة","الحياة اليومية","العبادات"],
 times:"مواقيت الصلاة",qibla:"القبلة",qiblaSub:"اعرف اتجاه الكعبة",duas:"الأدعية",duasSub:"الطعام، الخلاء، النوم، الشدة",
 dhikr:["سبحان الله","الحمد لله","الله أكبر"],dhikrSub:"اضغط على الدائرة. ثلاثًا وثلاثين مرة لكل منها بعد كل صلاة.",
 prayers:["الفجر","الظهر","العصر","المغرب","العشاء"],
 back:"رجوع",l11:"الوضوء خطوة بخطوة",l11lead:"الوضوء طهارة تسبق الصلاة. ذكره الله في القرآن، وبيّن الصحابي عثمان رضي الله عنه كيف كان النبي صلى الله عليه وسلم يتوضأ.",
 l11steps:["انوِ الوضوء بقلبك.","اغسل كفيك ثلاثًا.","تمضمض واستنشق ثم استنثر.","اغسل وجهك ثلاثًا من منابت الشعر إلى الذقن ومن الأذن إلى الأذن.","اغسل يدك اليمنى إلى المرفق ثلاثًا ثم اليسرى.","امسح رأسك مرة واحدة.","اغسل رجلك اليمنى إلى الكعبين ثلاثًا ثم اليسرى."],
 fromQuran:"من القرآن الكريم",fromHadith:"من السنة النبوية",verseNote:"نص الآية بالرسم المعتمد.",hadithNote:"نص الحديث مع حكمه من الدرر السنية.",
 key:"الفكرة الأساسية",keyT:"يشمل الوضوء غسل الوجه واليدين ومسح الرأس وغسل الرجلين بالترتيب قبل الصلاة.",tryT:"جرّب اليوم",tryTT:"توضأ مرة واحدة بهدوء متبعًا هذه الخطوات.",askM:"اسأل مرشدك",askMT:"عن الجبيرة أو الضماد أو طلاء الأظافر الذي يمنع وصول الماء.",
 done:"تم الدرس",doneOk:"أحسنت. الدرس ١٢ جاهز لك.",
 lessonsH:"رحلتك التعليمية",lessonsP:"أربعون درسًا قصيرًا بالترتيب الذي علّمه النبي صلى الله عليه وسلم لمعاذ: الإيمان أولًا، ثم الصلاة، ثم ما بعدها.",
 stageNames:["أسس الإيمان","الطهارة","الصلاة","الحياة اليومية","العبادات الأخرى"],lessonsWord:"دروس",completed:"مكتمل",open:"افتح",
 askH:"اسأل عن أي شيء",askP:"بلغتك. الإجابات من المصادر المعتمدة فقط، والأسئلة الشخصية تذهب إلى مرشدك.",ph:"اكتب سؤالك",send:"اسأل",
 sugg:["كيف أتوضأ؟","زوجتي مسيحية، هل ما زال زواجنا صحيحًا؟","هل «اطلبوا العلم ولو في الصين» حديث صحيح؟"],
 searching:"نبحث في المصادر المعتمدة…",sources:"المصادر",openLesson:"افتح الدرس كاملًا",
 refH:"هذا السؤال لمرشدك",refP:"سؤالك شخصي يتعلق بحالتك، ويحتاج إلى من يعرف التفاصيل. أرسلته إلى مرشدك، وسيظهر الرد هنا.",
 nfH:"لم نجده في مصادرنا",nfP:"لم أجد هذا القول في كتب الحديث التي نعتمدها، وهذا وحده لا يحكم على صحته. يظهر حكم الدرر السنية واسم العالم في التطبيق الكامل، ويمكن لمرشدك أن يوضح لك أكثر.",
 fallback:"في هذه المعاينة، جرّب أحد الأسئلة المقترحة. التطبيق الكامل يجيب عن أي سؤال.",
 mentorSays:"ردّ مرشدك",
 duasH:"أدعية كل يوم",duasP:"أدعية قصيرة من السنة مع مصدرها.",
 dcat:["قبل الطعام","عند دخول الخلاء","قبل النوم","عند الاستيقاظ","عند الكرب"],
 qH:"اتجاه القبلة",qP:"توجّه إلى هذا الاتجاه في الصلاة. على الجوال يدور القرص مع البوصلة.",qFrom:"من موقعك",qFromT:"من تبوك",qBtn:"استخدم موقعي",
 audio:"يُشغَّل هنا صوت حافظ الفريق في التطبيق الكامل."},
bn:{navHome:"আজ",navLessons:"পাঠ",navAsk:"প্রশ্ন",navDuas:"দোয়া",navQibla:"কিবলা",portal:"মেন্টর পোর্টাল",portalShort:"মেন্টর",
 greet:"আসসালামু আলাইকুম, করিম",heroP:"আপনার যাত্রার তিন সপ্তাহ চলছে। আজ একটি ছোট ধাপই যথেষ্ট।",nextK:"পরবর্তী নামাজ",inT:"বাকি",locNote:"আপনার অবস্থান অনুযায়ী সময়",locFallback:"তাবুকের সময়। আপনার শহরের জন্য লোকেশন চালু করুন।",
 todayStep:"আজকের ধাপ",lessonOf:"৪০টির মধ্যে ১১তম পাঠ",cont:"পাঠ চালিয়ে যান",stage:["ঈমান","পবিত্রতা","নামাজ","দৈনন্দিন জীবন","ইবাদত"],
 times:"নামাজের সময়",qibla:"কিবলা",qiblaSub:"কাবার দিক খুঁজুন",duas:"দোয়া",duasSub:"খাওয়া, টয়লেট, ঘুম, কঠিন সময়",
 dhikr:["সুবহানাল্লাহ","আলহামদুলিল্লাহ","আল্লাহু আকবার"],dhikrSub:"বৃত্তে চাপুন। প্রতি নামাজের পর প্রতিটি ৩৩ বার।",
 prayers:["ফজর","যোহর","আসর","মাগরিব","এশা"],
 back:"ফিরে যান",l11:"ধাপে ধাপে ওযু",l11lead:"ওযু হলো নামাজের আগের পবিত্রতা। আল্লাহ কুরআনে এর বর্ণনা দিয়েছেন, আর সাহাবি উসমান (রা.) দেখিয়েছেন নবী (সা.) কীভাবে ওযু করতেন।",
 l11steps:["মনে মনে ওযুর নিয়ত করুন।","দুই হাত তিনবার ধুয়ে নিন।","কুলি করুন, আর নাকে পানি দিয়ে ঝেড়ে ফেলুন।","কপালের চুল থেকে থুতনি পর্যন্ত এবং এক কান থেকে অন্য কান পর্যন্ত মুখ তিনবার ধুয়ে নিন।","ডান হাত কনুইসহ তিনবার ধুয়ে নিন, তারপর বাম হাত।","ভেজা হাতে একবার মাথা মাসেহ করুন।","ডান পা টাখনুসহ তিনবার ধুয়ে নিন, তারপর বাম পা।"],
 fromQuran:"কুরআন থেকে",fromHadith:"সুন্নাহ থেকে",verseNote:"আয়াতটি আরবিতে, বাদশাহ ফাহাদ কমপ্লেক্সের বাংলা অনুবাদসহ।",hadithNote:"হাদিসের পাঠ, Dorar.net-এর মানসহ।",
 key:"মূল কথা",keyT:"ওযুতে নামাজের আগে ক্রমানুসারে মুখ, হাত, মাথা ও পা ধোয়া হয়।",tryT:"আজ চেষ্টা করুন",tryTT:"এই ধাপগুলো মেনে ধীরে ধীরে একবার ওযু করুন।",askM:"মেন্টরকে জিজ্ঞেস করুন",askMT:"প্লাস্টার, ব্যান্ডেজ বা নেইল পলিশ থাকলে কী করবেন, যা ত্বকে পানি পৌঁছাতে বাধা দেয়।",
 done:"পাঠ শেষ",doneOk:"মাশাআল্লাহ। ১২তম পাঠ আপনার জন্য প্রস্তুত।",
 lessonsH:"আপনার শিক্ষাযাত্রা",lessonsP:"চল্লিশটি ছোট পাঠ, সেই ক্রমে যেভাবে নবী (সা.) মুআযকে শিখিয়েছিলেন: প্রথমে ঈমান, তারপর নামাজ, তারপর বাকিগুলো।",
 stageNames:["ঈমানের ভিত্তি","পবিত্রতা","নামাজ","দৈনন্দিন জীবন","অন্যান্য ইবাদত"],lessonsWord:"পাঠ",completed:"সম্পন্ন",open:"খুলুন",
 askH:"যেকোনো প্রশ্ন করুন",askP:"আপনার নিজের ভাষায়। উত্তর আসে শুধু অনুমোদিত উৎস থেকে, আর ব্যক্তিগত প্রশ্ন যায় আপনার মেন্টরের কাছে।",ph:"আপনার প্রশ্ন লিখুন",send:"প্রশ্ন",
 sugg:["কীভাবে ওযু করব?","আমার স্ত্রী খ্রিস্টান, আমাদের বিয়ে কি এখনো বৈধ?","\"জ্ঞান অর্জনে চীন পর্যন্ত যাও\" এটা কি হাদিস?"],
 searching:"অনুমোদিত উৎসে খোঁজা হচ্ছে…",sources:"উৎস",openLesson:"পুরো পাঠ খুলুন",
 refH:"এই প্রশ্নটি আপনার মেন্টরের জন্য",refP:"এটি আপনার নিজের পরিস্থিতি নিয়ে ব্যক্তিগত প্রশ্ন, তাই এমন কাউকে দরকার যিনি বিস্তারিত জানেন। প্রশ্নটি আপনার মেন্টরের কাছে পাঠানো হয়েছে, উত্তর এখানেই বাংলায় আসবে।",
 nfH:"আমাদের উৎসে পাওয়া যায়নি",nfP:"আমরা যে হাদিস সংকলন ব্যবহার করি, সেখানে এই কথাটি পাইনি। শুধু এ থেকে এর সত্যতা নির্ধারণ হয় না। পূর্ণ অ্যাপে Dorar.net-এর মান ও আলেমের নাম দেখানো হয়, আর আপনার মেন্টর আরও বলতে পারবেন।",
 fallback:"এই প্রিভিউতে প্রস্তাবিত প্রশ্নগুলোর একটি চেষ্টা করুন। পূর্ণ অ্যাপ যেকোনো প্রশ্নের উত্তর দেয়।",
 mentorSays:"আপনার মেন্টরের উত্তর",
 duasH:"প্রতিদিনের দোয়া",duasP:"সুন্নাহ থেকে ছোট দোয়া, অর্থ ও উৎসসহ।",
 dcat:["খাওয়ার আগে","টয়লেটে প্রবেশের সময়","ঘুমানোর আগে","ঘুম থেকে উঠে","কঠিন সময়ে"],
 qH:"কিবলার দিক",qP:"নামাজে এই দিকে মুখ করুন। মোবাইলে কম্পাসের সাথে ডায়াল ঘোরে।",qFrom:"আপনার অবস্থান থেকে",qFromT:"তাবুক থেকে",qBtn:"আমার লোকেশন ব্যবহার করুন",
 audio:"পূর্ণ অ্যাপে এখানে আমাদের হাফেজের কণ্ঠে অডিও বাজবে।"}};
const T2: Record<Lang, Record<string, any>> = {
en:{greet:"Assalamu alaikum",obStep:"Step",obOf:"of",ob1H:"Welcome to Mu'adh",ob1P:"A gentle guide for your first steps in Islam. Choose your language.",ob2H:"What should we call you?",ob2P:"Just a first name is fine.",ob2Ph:"Your name",ob3H:"A little about you",ob3P:"We only use this to plan your lessons. We never guess anything about you.",readQ:"Can you read Arabic?",readA:["Not yet","A little","Yes"],workQ:"When do you usually work?",workA:["Daytime","Night shifts","It changes"],ob4H:"Your journey is ready",ob4P:"Start with today's step. One small step a day is enough.",next:"Continue",skip:"Skip for now",start:"Start my journey",
 hintAudio:"With audio and transliteration",nightNote:"Night shifts: we'll remind you before each prayer, so none is missed while you sleep.",empty:"Begin your pursuit of knowledge.",
 permT:"To point you toward the Kaaba, Mu'adh needs location access.",permErr:"We couldn't find your location. Please check your device settings.",
 lessonsList:["Why purity matters","Ghusl: the full bath","Wudu step by step","What breaks wudu","Toilet manners","Tayammum"],playA:"Play audio for",hU:"h",mU:"min",mentorQ:"Referred questions",nightGreet:"Assalamu alaikum"},
ar:{greet:"السلام عليكم",obStep:"الخطوة",obOf:"من",ob1H:"مرحبًا بك في معاذ",ob1P:"دليل لطيف لخطواتك الأولى في الإسلام. اختر لغتك.",ob2H:"بماذا نناديك؟",ob2P:"الاسم الأول يكفي.",ob2Ph:"اسمك",ob3H:"قليلًا عنك",ob3P:"نستخدم هذا لترتيب دروسك فقط، ولا نستنتج عنك أي شيء.",readQ:"هل تقرأ العربية؟",readA:["ليس بعد","قليلًا","نعم"],workQ:"متى تعمل عادة؟",workA:["في النهار","مناوبات ليلية","يتغير"],ob4H:"رحلتك جاهزة",ob4P:"ابدأ بخطوة اليوم. خطوة صغيرة كل يوم تكفي.",next:"متابعة",skip:"تخطَّ الآن",start:"ابدأ رحلتي",
 hintAudio:"مع الصوت والكتابة اللاتينية",nightNote:"مناوبات ليلية: سنذكّرك قبل كل صلاة حتى لا تفوتك أثناء نومك.",empty:"ابدأ رحلتك في طلب العلم.",
 permT:"ليوجّهك معاذ نحو الكعبة يحتاج إلى إذن الوصول إلى الموقع.",permErr:"لم نتمكن من تحديد موقعك. يرجى التحقق من إعدادات جهازك.",
 lessonsList:["لماذا الطهارة مهمة","الغسل","الوضوء خطوة بخطوة","نواقض الوضوء","آداب قضاء الحاجة","التيمم"],playA:"تشغيل صوت",hU:"س",mU:"د",mentorQ:"الأسئلة المحالة",nightGreet:"السلام عليكم"},
bn:{greet:"আসসালামু আলাইকুম",obStep:"ধাপ",obOf:"এর",ob1H:"মুআযে আপনাকে স্বাগতম",ob1P:"ইসলামে আপনার প্রথম পদক্ষেপের জন্য একটি কোমল গাইড। আপনার ভাষা বেছে নিন।",ob2H:"আমরা আপনাকে কী নামে ডাকব?",ob2P:"শুধু প্রথম নামই যথেষ্ট।",ob2Ph:"আপনার নাম",ob3H:"আপনার সম্পর্কে একটু",ob3P:"এটি শুধু আপনার পাঠ সাজাতে ব্যবহার হয়। আমরা আপনার সম্পর্কে কিছু অনুমান করি না।",readQ:"আপনি কি আরবি পড়তে পারেন?",readA:["এখনো না","একটু","হ্যাঁ"],workQ:"আপনি সাধারণত কখন কাজ করেন?",workA:["দিনে","রাতের শিফটে","বদলায়"],ob4H:"আপনার যাত্রা প্রস্তুত",ob4P:"আজকের ধাপ দিয়ে শুরু করুন। প্রতিদিন একটি ছোট ধাপই যথেষ্ট।",next:"এগিয়ে যান",skip:"এখন বাদ দিন",start:"যাত্রা শুরু করুন",
 hintAudio:"অডিও ও উচ্চারণসহ",nightNote:"রাতের শিফট: প্রতিটি নামাজের আগে আমরা মনে করিয়ে দেব, যাতে ঘুমের মধ্যে কোনোটি ছুটে না যায়।",empty:"জ্ঞানের পথে যাত্রা শুরু করুন।",
 permT:"কাবার দিক দেখাতে মুআযের লোকেশনের অনুমতি প্রয়োজন।",permErr:"আপনার লোকেশন পাওয়া যায়নি। অনুগ্রহ করে ডিভাইসের সেটিংস দেখুন।",
 lessonsList:["পবিত্রতা কেন গুরুত্বপূর্ণ","গোসল","ধাপে ধাপে ওযু","ওযু ভঙ্গের কারণ","টয়লেটের আদব","তায়াম্মুম"],playA:"অডিও চালান",hU:"ঘণ্টা",mU:"মিনিট",mentorQ:"পাঠানো প্রশ্ন",nightGreet:"আসসালামু আলাইকুম"}};
(Object.keys(T2) as Lang[]).forEach((l) => Object.assign(T[l], T2[l]));
Object.assign(T.en, {tlH:"Today's prayers",stepW:"Step",ofW:"of",prev:"Previous",nextS:"Next step",allS:"See all steps",times3:"3 times",facing:"You are facing the Qibla",turnR:"Turn right",turnL:"Turn left",dist:"Distance to the Kaaba",km:"km",bearing:"Qibla direction",yourLoc:"Your location",enable:"Turn on compass",noComp:"Hold your phone flat. On a computer, use the arrow on the dial.",heading:"You are facing",viewAll:"See all"});
Object.assign(T.ar, {tlH:"صلوات اليوم",stepW:"الخطوة",ofW:"من",prev:"السابق",nextS:"الخطوة التالية",allS:"عرض كل الخطوات",times3:"ثلاث مرات",facing:"أنت متجه إلى القبلة",turnR:"استدر يمينًا",turnL:"استدر يسارًا",dist:"المسافة إلى الكعبة",km:"كم",bearing:"اتجاه القبلة",yourLoc:"موقعك",enable:"تشغيل البوصلة",noComp:"أمسك الجوال بشكل مستوٍ. على الحاسوب استخدم السهم على القرص.",heading:"اتجاهك الحالي",viewAll:"عرض الكل"});
Object.assign(T.bn, {tlH:"আজকের নামাজ",stepW:"ধাপ",ofW:"এর",prev:"আগের",nextS:"পরের ধাপ",allS:"সব ধাপ দেখুন",times3:"তিনবার",facing:"আপনি কিবলামুখী",turnR:"ডানে ঘুরুন",turnL:"বামে ঘুরুন",dist:"কাবা পর্যন্ত দূরত্ব",km:"কিমি",bearing:"কিবলার দিক",yourLoc:"আপনার অবস্থান",enable:"কম্পাস চালু করুন",noComp:"ফোনটি সমান করে ধরুন। কম্পিউটারে ডায়ালের তীর দেখুন।",heading:"আপনি যেদিকে মুখ করে আছেন",viewAll:"সব দেখুন"});
export const DUAS = [
 {ar:"بِسْمِ اللَّهِ",tr:"Bismillah",m:{en:"In the name of Allah.",bn:"আল্লাহর নামে।"},src:"Bukhari 5376, Muslim 2022"},
 {ar:"اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",tr:"Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",m:{en:"O Allah, I seek refuge in You from evil and evil beings.",bn:"হে আল্লাহ, আমি আপনার কাছে অনিষ্ট ও অনিষ্টকারী থেকে আশ্রয় চাই।"},src:"Bukhari 142, Muslim 375"},
 {ar:"بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",tr:"Bismika Allahumma amutu wa ahya",m:{en:"In Your name, O Allah, I die and I live.",bn:"হে আল্লাহ, আপনার নামেই আমি মরি ও বাঁচি।"},src:"Bukhari 6312"},
 {ar:"الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",tr:"Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",m:{en:"All praise is for Allah, who gave us life after He caused us to die, and to Him is the return.",bn:"সব প্রশংসা আল্লাহর, যিনি আমাদের মৃত্যুর পর জীবিত করেছেন, আর তাঁর কাছেই ফিরে যেতে হবে।"},src:"Bukhari 6312"},
 {ar:"لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",tr:"La ilaha illallahul-'Azimul-Halim...",m:{en:"There is no god but Allah, the Almighty, the Forbearing. There is no god but Allah, Lord of the great Throne. There is no god but Allah, Lord of the heavens, Lord of the earth, and Lord of the noble Throne.",bn:"আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি মহান ও সহনশীল। আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি মহান আরশের রব। আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি আসমান, জমিন ও সম্মানিত আরশের রব।"},src:"Bukhari 6346, Muslim 2730"}];
export default T;
